const modules = [
  ['dashboard', 'layout-dashboard', 'Dashboard'], ['officers', 'users', 'Officers'], ['tasks', 'list-checks', 'Tasks'],
  ['training', 'graduation-cap', 'Training'], ['supervision', 'user-round-check', 'Supervision'], ['reports', 'chart-no-axes-combined', 'Reports'],
];
const officers = [
  { initials: 'HT', name: 'harry_ted', rank: 'Inspector', callsign: '711', team: 'MO8 Command', status: 'On duty', activity: '14h 32m', training: 'Advanced + TPAC', tone: 'blue' },
  { initials: 'CA', name: 'Caeltus', rank: 'Inspector', callsign: '710', team: 'Road Crime Team', status: 'Available', activity: '11h 08m', training: 'Advanced', tone: 'teal' },
  { initials: 'ST', name: 'Santorcra_2008', rank: 'Sergeant', callsign: '2101', team: 'Roads Policing', status: 'On duty', activity: '9h 45m', training: 'Response', tone: 'green' },
  { initials: 'AM', name: 'ArmyManTheGreatest', rank: 'Sergeant', callsign: '2102', team: 'Road Crime Team', status: 'LOA', activity: '7h 12m', training: 'Advanced', tone: 'amber' },
  { initials: 'JV', name: 'Jv4cks', rank: 'Police Constable', callsign: '2106', team: 'Roads Policing', status: 'Available', activity: '6h 28m', training: 'IPP', tone: 'slate' },
];
const tasks = [
  { priority: 'High', title: 'Review shift debrief', officer: 'Santorcra_2008', meta: 'Submitted 18 minutes ago', type: 'Shift review' },
  { priority: 'Normal', title: 'Approve leave request', officer: 'Jv4cks', meta: '12–16 July 2026', type: 'LOA' },
  { priority: 'High', title: 'AIP manager signature', officer: 'nonomehjk', meta: 'Due today', type: 'Signature' },
  { priority: 'Normal', title: 'Course booking requests', officer: 'Response Driving', meta: '3 awaiting decision', type: 'Training' },
  { priority: 'Low', title: 'Monthly supervisor check-in', officer: 'ArmyManTheGreatest', meta: 'Due in 4 days', type: 'Development' },
];
const notifications = [
  ['critical', 'Shift amendment returned', 'CAD review notes require your attention.', '8 min'],
  ['positive', 'Leave approved', 'Your leave request for 12–16 July was approved.', '34 min'],
  ['normal', 'New supervisor message', 'Caeltus sent an update about your development plan.', '1 hr'],
];
let activeView = 'dashboard';

function icon(name) { return `<i data-lucide="${name}"></i>`; }
function renderNavigation() {
  const html = modules.map(([view, iconName, label]) => `<button data-view="${view}" class="${view === activeView ? 'active' : ''}">${icon(iconName)}<span>${label}</span>${view === 'tasks' ? '<b>5</b>' : ''}</button>`).join('');
  document.querySelector('.primary-navigation').innerHTML = html;
  document.querySelector('.portal-nav').innerHTML = modules.slice(0, 5).map(([view,,label]) => `<button data-view="${view}" class="${view === activeView ? 'active' : ''}">${label}${view === 'tasks' ? '<b>5</b>' : ''}</button>`).join('');
}
function officerRow(officer, compact = false) {
  return `<button class="officer-row ${compact ? 'compact' : ''}" data-officer="${officer.name}"><span class="officer-avatar tone-${officer.tone}">${officer.initials}</span><span><strong>${officer.name}</strong><small>${officer.rank} / ${officer.callsign}</small></span><em class="status-${officer.status.toLowerCase().replace(' ', '-')}">${officer.status}</em>${compact ? '' : `<span>${officer.team}</span><span>${officer.activity}</span>${icon('chevron-right')}`}</button>`;
}
function renderRecordList(query = '') {
  const filtered = officers.filter((o) => `${o.name} ${o.rank} ${o.callsign}`.toLowerCase().includes(query.toLowerCase()));
  document.querySelector('#recordList').innerHTML = filtered.map((o) => officerRow(o, true)).join('') || '<p class="empty">No officers found.</p>';
}
function stat(label, value, detail, iconName, tone = '') { return `<article class="metric ${tone}"><div>${icon(iconName)}<span>${label}</span></div><strong>${value}</strong><small>${detail}</small></article>`; }
function dashboardView() {
  return `<section class="metric-grid">${stat('On duty now','8','2 active callsigns','radio','positive')}${stat('My open tasks','5','2 high priority','list-checks','attention')}${stat('Team activity','92h 18m','Last 30 days','clock-3')}${stat('Training coverage','84%','3 gaps identified','shield-check')}</section>
  <section class="content-layout"><div class="primary-column"><section class="workspace-section"><header><div><span>Priority queue</span><h2>My tasks</h2></div><button data-view="tasks">View all ${icon('arrow-right')}</button></header><div class="task-list">${tasks.slice(0,3).map(taskRow).join('')}</div></section><section class="workspace-section"><header><div><span>Live personnel</span><h2>Team status</h2></div><button data-view="officers">Open roster ${icon('arrow-right')}</button></header><div class="officer-table"><div class="table-heading"><span>Officer</span><span>Team</span><span>30-day activity</span><span></span></div>${officers.slice(0,4).map((o) => officerRow(o)).join('')}</div></section></div><aside class="secondary-column"><section class="workspace-section notice-panel"><header><div><span>Command update</span><h2>Notice board</h2></div></header><article><time>08 JUL</time><div><strong>Operational standards update</strong><p>Revised vehicle stop recording guidance is now available.</p><button>Read update</button></div></article><article><time>06 JUL</time><div><strong>Response driving course</strong><p>Three remaining places for Saturday’s course.</p></div></article></section><section class="workspace-section mini-calendar"><header><div><span>Coming up</span><h2>My calendar</h2></div></header><article><b>10</b><span><strong>Supervisor check-in</strong><small>19:30 / Microsoft Teams</small></span></article><article><b>12</b><span><strong>Response driving</strong><small>18:00 / Training Centre</small></span></article></section></aside></section>`;
}
function taskRow(task) { return `<button class="task-row" data-task="${task.title}"><span class="priority priority-${task.priority.toLowerCase()}">${task.priority}</span><span><strong>${task.title}</strong><small>${task.officer} / ${task.type}</small></span><time>${task.meta}</time>${icon('arrow-up-right')}</button>`; }
function officersView() {
  return `<section class="page-command"><div class="search-box">${icon('search')}<input id="officerPageSearch" placeholder="Search username, callsign, rank or team"></div><button class="secondary">${icon('list-filter')} Filter</button><button>${icon('user-plus')} Add officer</button></section><section class="workspace-section roster-section"><header><div><span>Personnel database</span><h2>Active officers</h2></div><div class="view-toggle"><button class="active">${icon('list')}</button><button>${icon('layout-grid')}</button></div></header><div class="officer-table full"><div class="table-heading"><span>Officer</span><span>Team</span><span>30-day activity</span><span></span></div>${officers.map((o) => officerRow(o)).join('')}</div></section>`;
}
function tasksView() { return `<section class="task-board-head"><div class="task-scope"><button class="active">My tasks <b>5</b></button><button>Team queue <b>18</b></button><button>Completed</button></div><button>${icon('plus')} Assign task</button></section><section class="task-board"><div><header><span>High priority</span><b>2</b></header>${tasks.filter(t=>t.priority==='High').map(taskCard).join('')}</div><div><header><span>In progress</span><b>2</b></header>${tasks.filter(t=>t.priority==='Normal').map(taskCard).join('')}</div><div><header><span>Upcoming</span><b>1</b></header>${tasks.filter(t=>t.priority==='Low').map(taskCard).join('')}</div></section>`; }
function taskCard(task) { return `<article class="task-card" data-task="${task.title}"><span class="priority priority-${task.priority.toLowerCase()}">${task.priority}</span><h3>${task.title}</h3><p>${task.officer}</p><footer><small>${task.meta}</small><button>${icon('arrow-right')}</button></footer></article>`; }
function trainingView() { return `<section class="metric-grid three">${stat('Current qualifications','47','Across 22 officers','badge-check')}${stat('Expiring soon','4','Within 30 days','triangle-alert','attention')}${stat('Upcoming courses','3','11 available places','calendar-check','positive')}</section><section class="workspace-section"><header><div><span>Capability overview</span><h2>Training matrix</h2></div><button>${icon('calendar-plus')} Create course</button></header><div class="training-matrix"><div class="training-head"><span>Officer</span><span>Taser</span><span>MOE</span><span>Motorbike</span><span>Driving</span></div>${officers.map((o,i)=>`<button data-officer="${o.name}"><span><strong>${o.name}</strong><small>${o.rank}</small></span><i class="tick ${i<3?'held':''}"></i><i class="tick ${i===1?'held':''}"></i><i class="tick ${i>2?'held':''}"></i><em>${o.training}</em></button>`).join('')}</div></section>`; }
function genericView(title, iconName) { return `<section class="empty-workspace">${icon(iconName)}<span>Structural prototype</span><h2>${title}</h2><p>This area demonstrates how another Personnel module would inherit the selected navigation and workspace model.</p><button data-view="dashboard">Return to dashboard</button></section>`; }
function renderView(view) {
  activeView = view; renderNavigation();
  const labels = { dashboard:['Personnel overview','Good evening, Inspector'], officers:['Personnel database','Officer records'], tasks:['Action centre','Tasks and approvals'], training:['Learning and capability','Training'], supervision:['Line management','Supervision'], reports:['Assurance and insight','Reports'], calendar:['Schedule','Calendar'], documents:['Knowledge centre','Documents'], messages:['Internal communications','Messages'] };
  const [eyebrow,title] = labels[view] || labels.dashboard;
  document.querySelector('#workspaceEyebrow').textContent = eyebrow; document.querySelector('#workspaceTitle').textContent = title; document.querySelector('#activeTabLabel').textContent = title;
  const content = view==='dashboard'?dashboardView():view==='officers'?officersView():view==='tasks'?tasksView():view==='training'?trainingView():genericView(title, view==='documents'?'folder-open':view==='messages'?'message-square':'panels-top-left');
  document.querySelector('#workspaceContent').innerHTML = content; document.body.classList.remove('mobile-nav-open'); document.querySelector('#mobileScrim').hidden = true;
  lucide.createIcons();
}
function renderContext() { document.querySelector('#contextContent').innerHTML = tasks.slice(0,4).map((t)=>`<button class="context-task" data-task="${t.title}"><span class="priority priority-${t.priority.toLowerCase()}"></span><div><strong>${t.title}</strong><small>${t.officer}</small><time>${t.meta}</time></div>${icon('chevron-right')}</button>`).join(''); }
function showOfficer(name) { const o=officers.find(x=>x.name===name); if(!o)return; openDialog('Officer record',o.name,`<section class="profile-summary"><span class="officer-avatar large tone-${o.tone}">${o.initials}</span><div><span>${o.rank}</span><h3>${o.name}</h3><p>${o.callsign} / ${o.team}</p></div><em class="status-${o.status.toLowerCase().replace(' ','-')}">${o.status}</em></section><dl class="record-facts"><div><dt>Supervisor</dt><dd>Caeltus</dd></div><div><dt>30-day activity</dt><dd>${o.activity}</dd></div><div><dt>Driving</dt><dd>${o.training}</dd></div><div><dt>Open tasks</dt><dd>2</dd></div></dl><nav class="record-tabs"><button class="active">Overview</button><button>Activity</button><button>Training</button><button>Development</button></nav><section class="record-timeline"><article><i></i><div><strong>Shift completed</strong><p>2h 18m / 3 CADs attended / Quality 92%</p><time>Yesterday, 22:14</time></div></article><article><i></i><div><strong>Supervisor check-in</strong><p>Monthly development review completed.</p><time>03 July 2026</time></div></article></section>`); }
function showTask(title) { const t=tasks.find(x=>x.title===title); if(!t)return; openDialog('Task review',t.title,`<section class="task-detail"><span class="priority priority-${t.priority.toLowerCase()}">${t.priority}</span><h3>${t.officer}</h3><p>${t.meta}</p><div><strong>Required action</strong><p>Review the linked record and record the appropriate decision or follow-up action.</p></div><footer><button class="secondary" data-close-dialog>Close</button><button>Open task workspace</button></footer></section>`); }
function openDialog(eyebrow,title,html){document.querySelector('#dialogEyebrow').textContent=eyebrow;document.querySelector('#dialogTitle').textContent=title;document.querySelector('#dialogContent').innerHTML=html;document.querySelector('#prototypeDialog').showModal();lucide.createIcons();}
function setConcept(concept){document.body.dataset.concept=concept;document.querySelectorAll('[data-concept-button]').forEach(b=>b.classList.toggle('active',b.dataset.conceptButton===concept));localStorage.setItem('mo8_prototype_concept',concept);renderView(activeView);}
function toggleNotifications(open=true){const drawer=document.querySelector('#notificationDrawer');drawer.hidden=!open;if(open){document.querySelector('#notificationItems').innerHTML=notifications.map(([tone,title,text,time])=>`<article class="notice-${tone}"><i></i><div><strong>${title}</strong><p>${text}</p><time>${time}</time></div></article>`).join('');}}
document.addEventListener('click',(e)=>{const concept=e.target.closest('[data-concept-button]');if(concept)setConcept(concept.dataset.conceptButton);const view=e.target.closest('[data-view]');if(view)renderView(view.dataset.view);const tb=e.target.closest('[data-taskbar-view]');if(tb)renderView(tb.dataset.taskbarView);const officer=e.target.closest('[data-officer]');if(officer)showOfficer(officer.dataset.officer);const task=e.target.closest('[data-task]');if(task)showTask(task.dataset.task);if(e.target.closest('[data-close-dialog]'))document.querySelector('#prototypeDialog').close();});
document.querySelector('#recordSearch').addEventListener('input',e=>renderRecordList(e.target.value));
document.querySelector('#prototypeNotifications').addEventListener('click',()=>toggleNotifications(true));document.querySelector('#closeNotifications').addEventListener('click',()=>toggleNotifications(false));
document.querySelector('#mobileNavButton').addEventListener('click',()=>{document.body.classList.toggle('mobile-nav-open');document.querySelector('#mobileScrim').hidden=!document.body.classList.contains('mobile-nav-open');});document.querySelector('#mobileScrim').addEventListener('click',()=>{document.body.classList.remove('mobile-nav-open');document.querySelector('#mobileScrim').hidden=true;});
document.querySelector('#studioInfo').addEventListener('click',()=>openDialog('Prototype studio','About this experiment','<section class="about-prototype"><p>Each concept uses the same sample records and interactions, but changes the navigation model, information hierarchy and workspace structure.</p><p>No live MDT data is loaded or changed here.</p></section>'));
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector('#globalPrototypeSearch').focus();}if(e.key==='Escape')toggleNotifications(false);});
renderRecordList();renderContext();setConcept(localStorage.getItem('mo8_prototype_concept')||'desktop');lucide.createIcons();
